name: Create CDS Test branch

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy xmpls
        run: npm run add-all-xmpls
      - name: Extract last commit author email and name
        id: extract_commit_info
        run: |
          LAST_COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
          LAST_COMMIT_NAME=$(git log -1 --pretty=format:'%an')
          echo "AUTHOR_EMAIL=$LAST_COMMIT_EMAIL" >> $GITHUB_ENV
          echo "AUTHOR_NAME=$LAST_COMMIT_NAME" >> $GITHUB_ENV
          

      - name: Push
        run: |
          git config --global user.email "${{ env.AUTHOR_EMAIL }}"
          git config --global user.name "${{ env.AUTHOR_NAME }}"
          git add .
          git push --force-with-lease origin HEAD:cds-test-integrate
#git commit -m "${{ github.event.head_commit.message }}"
          
#git push origin cds-test-integrate
